### ISSUE TITLE
Update upstream nx-remotecache-custom dep to > v5

### ISSUE THREAD

**Issue by comp615** [John98Zakaria/nx-remotecache-gcp#3]
See this issue: https://github.com/NiklasPor/nx-remotecache-custom/issues/26
Fixes: `The local cache artifact in "*" was not been generated on this machine.`

Currently fixable by adding a manual dependency override in `package.json`:
```
"overrides": {
    "nx-remotecache-gcp": {
      "nx-remotecache-custom": "^5.0.0"
    }
  },
```

Fairly trivial update, but wasn't sure if that means this package should update major version too? Might make sense to version it to v5 just to be in sync with the -custom upstream.

**Comment by SergeAstapov** [comment]
Appears this has been completed and `nx-remotecache-gcp` now depends on `"nx-remotecache-custom": "^5.0.1"`.

However, now this package needs to depend on nx-remotecache-custom@17 per https://github.com/NiklasPor/nx-remotecache-custom/pull/28

**Comment by John98Zakaria** [comment]
Oh I'll updated the package :)

**Comment by John98Zakaria** [comment]
Done

**Comment by John98Zakaria** [comment]
I have added dependabot and subscribed to the repository to get notified next time
