### ISSUE TITLE
Separate out GCP options?

### ISSUE THREAD

**Issue by larsivi** [John98Zakaria/nx-remotecache-gcp#64]
This is not really an issue with this package, as it works perfectly.

However, I am creating a backend for i18next using the GCS buckets. Your file gcp-specific is basically a big part of what I need (minus the nx stuff, possibly plus some i18next stuff), so I wondered if you would consider making that a package of its own?

I haven't looked at the feasibility, I just wanted to avoid copying most of the code if possible. Edit: Wiht proper attribution of course!

**Comment by John98Zakaria** [comment]
I am very flattered by the fact that you want to copy the code.

I don't find it reasonable to create a new package just for the gcp configuration, it would feel to me like an `is-even` package :sweat_smile: 

Feel free to copy the code :)
